// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transfer} from '../models';

export function Transfer(arg1:transfer.Options):Promise<void>;
